fix: chart release

diff --git a/.ci/task-release.yaml b/.ci/task-release.yaml
--- a/.ci/task-release.yaml
+++ b/.ci/task-release.yaml
@@ -11,8 +11,9 @@ outputs:
 run:
   path: bash
   args:
-  - -cxe
+  - -cx
   - |
+    TASK_ROOT=$(pwd)
     cd repo
     git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
     git fetch --all
@@ -21,15 +22,16 @@ run:
     git config --global user.name concourse
     printf "packaging chart"
     export HELM_CONFIG_HOME=./
-    for chart in $(ct list-changed); do
+    for chart in $(ct list-changed --config ct.yaml); do
       echo "Building Chart $chart"
-      helm dependency build $chart
-      helm package $chart
+      helm package -u -d ../charts/charts $
+      [[ -z ${SKIP_ERR} && $? != 0 ]] && echo "######## Error when packaging chart #######" && exit 1
     done
-    mv *.tgz ../charts/charts/
-    cd ../charts
-    ls
+    cd ${TASK_ROOT}/charts
+    git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
+    git fetch --all
     helm repo index --url https://improwised.github.io/charts .
+    [[ -z ${SKIP_ERR} && $? != 0 ]] && echo "######## Error when creating index #######" && exit 1
     cat index.yaml
     git add .
     git commit -m "releases $(date '+%Y-%m-%d-%H-%M-%S')" --allow-empty
